"""create book, publisher, category and author

Revision ID: 35df9d26e45c
Revises: 94d3e44e5803
Create Date: 2023-10-19 21:13:40.781384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35df9d26e45c'
down_revision: Union[str, None] = '94d3e44e5803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
